# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/RayTracer/RayTracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/RayTracer/RayTracer/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/RayTracer/RayTracer/build/CMakeFiles /home/runner/work/RayTracer/RayTracer/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/RayTracer/RayTracer/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/runner/work/RayTracer/RayTracer/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raytrace_lib

# Build rule for target.
raytrace_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raytrace_lib
.PHONY : raytrace_lib

# fast build rule for target.
raytrace_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/build
.PHONY : raytrace_lib/fast

#=============================================================================
# Target rules for targets named RayTracer

# Build rule for target.
RayTracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RayTracer
.PHONY : RayTracer

# fast build rule for target.
RayTracer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RayTracer.dir/build.make CMakeFiles/RayTracer.dir/build
.PHONY : RayTracer/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/Experimental.dir/build.make _deps/yaml-cpp-build/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/Nightly.dir/build.make _deps/yaml-cpp-build/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/Continuous.dir/build.make _deps/yaml-cpp-build/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyMemoryCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyStart.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyUpdate.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyConfigure.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyBuild.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyTest.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyCoverage.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyMemCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlySubmit.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalStart.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalUpdate.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalConfigure.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalBuild.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalTest.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalCoverage.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalMemCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalSubmit.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousStart.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousUpdate.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousConfigure.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousBuild.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousTest.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousCoverage.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousMemCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousSubmit.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named yaml-cpp

# Build rule for target.
yaml-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp
.PHONY : yaml-cpp

# fast build rule for target.
yaml-cpp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/yaml-cpp.dir/build.make _deps/yaml-cpp-build/CMakeFiles/yaml-cpp.dir/build
.PHONY : yaml-cpp/fast

#=============================================================================
# Target rules for targets named yaml-cpp-sandbox

# Build rule for target.
yaml-cpp-sandbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-sandbox
.PHONY : yaml-cpp-sandbox

# fast build rule for target.
yaml-cpp-sandbox/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox.dir/build
.PHONY : yaml-cpp-sandbox/fast

#=============================================================================
# Target rules for targets named yaml-cpp-parse

# Build rule for target.
yaml-cpp-parse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-parse
.PHONY : yaml-cpp-parse

# fast build rule for target.
yaml-cpp-parse/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse.dir/build
.PHONY : yaml-cpp-parse/fast

#=============================================================================
# Target rules for targets named yaml-cpp-read

# Build rule for target.
yaml-cpp-read: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-read
.PHONY : yaml-cpp-read

# fast build rule for target.
yaml-cpp-read/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read.dir/build
.PHONY : yaml-cpp-read/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RayTracer.dir/build.make CMakeFiles/RayTracer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RayTracer.dir/build.make CMakeFiles/RayTracer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RayTracer.dir/build.make CMakeFiles/RayTracer.dir/main.cpp.s
.PHONY : main.cpp.s

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Canvas.o: src/Canvas.cpp.o
.PHONY : src/Canvas.o

# target to build an object file
src/Canvas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Canvas.cpp.o
.PHONY : src/Canvas.cpp.o

src/Canvas.i: src/Canvas.cpp.i
.PHONY : src/Canvas.i

# target to preprocess a source file
src/Canvas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Canvas.cpp.i
.PHONY : src/Canvas.cpp.i

src/Canvas.s: src/Canvas.cpp.s
.PHONY : src/Canvas.s

# target to generate assembly for a file
src/Canvas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Canvas.cpp.s
.PHONY : src/Canvas.cpp.s

src/Comps.o: src/Comps.cpp.o
.PHONY : src/Comps.o

# target to build an object file
src/Comps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Comps.cpp.o
.PHONY : src/Comps.cpp.o

src/Comps.i: src/Comps.cpp.i
.PHONY : src/Comps.i

# target to preprocess a source file
src/Comps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Comps.cpp.i
.PHONY : src/Comps.cpp.i

src/Comps.s: src/Comps.cpp.s
.PHONY : src/Comps.s

# target to generate assembly for a file
src/Comps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Comps.cpp.s
.PHONY : src/Comps.cpp.s

src/Cube.o: src/Cube.cpp.o
.PHONY : src/Cube.o

# target to build an object file
src/Cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Cube.cpp.o
.PHONY : src/Cube.cpp.o

src/Cube.i: src/Cube.cpp.i
.PHONY : src/Cube.i

# target to preprocess a source file
src/Cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Cube.cpp.i
.PHONY : src/Cube.cpp.i

src/Cube.s: src/Cube.cpp.s
.PHONY : src/Cube.s

# target to generate assembly for a file
src/Cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Cube.cpp.s
.PHONY : src/Cube.cpp.s

src/IntersectionList.o: src/IntersectionList.cpp.o
.PHONY : src/IntersectionList.o

# target to build an object file
src/IntersectionList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/IntersectionList.cpp.o
.PHONY : src/IntersectionList.cpp.o

src/IntersectionList.i: src/IntersectionList.cpp.i
.PHONY : src/IntersectionList.i

# target to preprocess a source file
src/IntersectionList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/IntersectionList.cpp.i
.PHONY : src/IntersectionList.cpp.i

src/IntersectionList.s: src/IntersectionList.cpp.s
.PHONY : src/IntersectionList.s

# target to generate assembly for a file
src/IntersectionList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/IntersectionList.cpp.s
.PHONY : src/IntersectionList.cpp.s

src/Light.o: src/Light.cpp.o
.PHONY : src/Light.o

# target to build an object file
src/Light.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Light.cpp.o
.PHONY : src/Light.cpp.o

src/Light.i: src/Light.cpp.i
.PHONY : src/Light.i

# target to preprocess a source file
src/Light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Light.cpp.i
.PHONY : src/Light.cpp.i

src/Light.s: src/Light.cpp.s
.PHONY : src/Light.s

# target to generate assembly for a file
src/Light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Light.cpp.s
.PHONY : src/Light.cpp.s

src/Material.o: src/Material.cpp.o
.PHONY : src/Material.o

# target to build an object file
src/Material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Material.cpp.o
.PHONY : src/Material.cpp.o

src/Material.i: src/Material.cpp.i
.PHONY : src/Material.i

# target to preprocess a source file
src/Material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Material.cpp.i
.PHONY : src/Material.cpp.i

src/Material.s: src/Material.cpp.s
.PHONY : src/Material.s

# target to generate assembly for a file
src/Material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Material.cpp.s
.PHONY : src/Material.cpp.s

src/Noise.o: src/Noise.cpp.o
.PHONY : src/Noise.o

# target to build an object file
src/Noise.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Noise.cpp.o
.PHONY : src/Noise.cpp.o

src/Noise.i: src/Noise.cpp.i
.PHONY : src/Noise.i

# target to preprocess a source file
src/Noise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Noise.cpp.i
.PHONY : src/Noise.cpp.i

src/Noise.s: src/Noise.cpp.s
.PHONY : src/Noise.s

# target to generate assembly for a file
src/Noise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Noise.cpp.s
.PHONY : src/Noise.cpp.s

src/Pattern.o: src/Pattern.cpp.o
.PHONY : src/Pattern.o

# target to build an object file
src/Pattern.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Pattern.cpp.o
.PHONY : src/Pattern.cpp.o

src/Pattern.i: src/Pattern.cpp.i
.PHONY : src/Pattern.i

# target to preprocess a source file
src/Pattern.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Pattern.cpp.i
.PHONY : src/Pattern.cpp.i

src/Pattern.s: src/Pattern.cpp.s
.PHONY : src/Pattern.s

# target to generate assembly for a file
src/Pattern.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Pattern.cpp.s
.PHONY : src/Pattern.cpp.s

src/Plane.o: src/Plane.cpp.o
.PHONY : src/Plane.o

# target to build an object file
src/Plane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Plane.cpp.o
.PHONY : src/Plane.cpp.o

src/Plane.i: src/Plane.cpp.i
.PHONY : src/Plane.i

# target to preprocess a source file
src/Plane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Plane.cpp.i
.PHONY : src/Plane.cpp.i

src/Plane.s: src/Plane.cpp.s
.PHONY : src/Plane.s

# target to generate assembly for a file
src/Plane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Plane.cpp.s
.PHONY : src/Plane.cpp.s

src/Shape.o: src/Shape.cpp.o
.PHONY : src/Shape.o

# target to build an object file
src/Shape.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Shape.cpp.o
.PHONY : src/Shape.cpp.o

src/Shape.i: src/Shape.cpp.i
.PHONY : src/Shape.i

# target to preprocess a source file
src/Shape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Shape.cpp.i
.PHONY : src/Shape.cpp.i

src/Shape.s: src/Shape.cpp.s
.PHONY : src/Shape.s

# target to generate assembly for a file
src/Shape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Shape.cpp.s
.PHONY : src/Shape.cpp.s

src/Sphere.o: src/Sphere.cpp.o
.PHONY : src/Sphere.o

# target to build an object file
src/Sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Sphere.cpp.o
.PHONY : src/Sphere.cpp.o

src/Sphere.i: src/Sphere.cpp.i
.PHONY : src/Sphere.i

# target to preprocess a source file
src/Sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Sphere.cpp.i
.PHONY : src/Sphere.cpp.i

src/Sphere.s: src/Sphere.cpp.s
.PHONY : src/Sphere.s

# target to generate assembly for a file
src/Sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Sphere.cpp.s
.PHONY : src/Sphere.cpp.s

src/Transformations.o: src/Transformations.cpp.o
.PHONY : src/Transformations.o

# target to build an object file
src/Transformations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Transformations.cpp.o
.PHONY : src/Transformations.cpp.o

src/Transformations.i: src/Transformations.cpp.i
.PHONY : src/Transformations.i

# target to preprocess a source file
src/Transformations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Transformations.cpp.i
.PHONY : src/Transformations.cpp.i

src/Transformations.s: src/Transformations.cpp.s
.PHONY : src/Transformations.s

# target to generate assembly for a file
src/Transformations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Transformations.cpp.s
.PHONY : src/Transformations.cpp.s

src/Tuple.o: src/Tuple.cpp.o
.PHONY : src/Tuple.o

# target to build an object file
src/Tuple.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Tuple.cpp.o
.PHONY : src/Tuple.cpp.o

src/Tuple.i: src/Tuple.cpp.i
.PHONY : src/Tuple.i

# target to preprocess a source file
src/Tuple.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Tuple.cpp.i
.PHONY : src/Tuple.cpp.i

src/Tuple.s: src/Tuple.cpp.s
.PHONY : src/Tuple.s

# target to generate assembly for a file
src/Tuple.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/Tuple.cpp.s
.PHONY : src/Tuple.cpp.s

src/World.o: src/World.cpp.o
.PHONY : src/World.o

# target to build an object file
src/World.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/World.cpp.o
.PHONY : src/World.cpp.o

src/World.i: src/World.cpp.i
.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s
.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

src/YamlParser.o: src/YamlParser.cpp.o
.PHONY : src/YamlParser.o

# target to build an object file
src/YamlParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/YamlParser.cpp.o
.PHONY : src/YamlParser.cpp.o

src/YamlParser.i: src/YamlParser.cpp.i
.PHONY : src/YamlParser.i

# target to preprocess a source file
src/YamlParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/YamlParser.cpp.i
.PHONY : src/YamlParser.cpp.i

src/YamlParser.s: src/YamlParser.cpp.s
.PHONY : src/YamlParser.s

# target to generate assembly for a file
src/YamlParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytrace_lib.dir/build.make CMakeFiles/raytrace_lib.dir/src/YamlParser.cpp.s
.PHONY : src/YamlParser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... RayTracer"
	@echo "... raytrace_lib"
	@echo "... yaml-cpp"
	@echo "... yaml-cpp-parse"
	@echo "... yaml-cpp-read"
	@echo "... yaml-cpp-sandbox"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Canvas.o"
	@echo "... src/Canvas.i"
	@echo "... src/Canvas.s"
	@echo "... src/Comps.o"
	@echo "... src/Comps.i"
	@echo "... src/Comps.s"
	@echo "... src/Cube.o"
	@echo "... src/Cube.i"
	@echo "... src/Cube.s"
	@echo "... src/IntersectionList.o"
	@echo "... src/IntersectionList.i"
	@echo "... src/IntersectionList.s"
	@echo "... src/Light.o"
	@echo "... src/Light.i"
	@echo "... src/Light.s"
	@echo "... src/Material.o"
	@echo "... src/Material.i"
	@echo "... src/Material.s"
	@echo "... src/Noise.o"
	@echo "... src/Noise.i"
	@echo "... src/Noise.s"
	@echo "... src/Pattern.o"
	@echo "... src/Pattern.i"
	@echo "... src/Pattern.s"
	@echo "... src/Plane.o"
	@echo "... src/Plane.i"
	@echo "... src/Plane.s"
	@echo "... src/Shape.o"
	@echo "... src/Shape.i"
	@echo "... src/Shape.s"
	@echo "... src/Sphere.o"
	@echo "... src/Sphere.i"
	@echo "... src/Sphere.s"
	@echo "... src/Transformations.o"
	@echo "... src/Transformations.i"
	@echo "... src/Transformations.s"
	@echo "... src/Tuple.o"
	@echo "... src/Tuple.i"
	@echo "... src/Tuple.s"
	@echo "... src/World.o"
	@echo "... src/World.i"
	@echo "... src/World.s"
	@echo "... src/YamlParser.o"
	@echo "... src/YamlParser.i"
	@echo "... src/YamlParser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/runner/work/RayTracer/RayTracer/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

